### ISSUE TITLE
수집이 잘 안되는 것 같아요.

### ISSUE THREAD

**Issue by ahribori** [10duck/issues#1]
우선 재미있는 프로젝트 구경 잘 했습니다:)
제가 데일리커밋을 한지 거의 1년이 지났는데요~
데이터 수집 주기가 텀이 긴건지, 수집이 잘 안되는건지 데이터가 조금밖에 안나오네요.
궁금해서 문의드려요~!

**Comment by kingbbode** [comment]
안녕하세요! 문의주셔서 감사합니다 :)

1. 시즌제를 운영하고 있습니다!
월 단위로 시즌제를 운영하고 있습니다. 현재 오픈 베타는 10월 1일 데이터 기준으로 수집이 되고 있습니다.
데이터 수집 기간을 표기하도록 해야겠네요!

2. private 저장소의 데이터는 수집되지 않습니다.
꾸준함 수치에 대해서는 private 저장소의 수치를 사용하지만, 활동 내역에서는 private 저장소의 데이터는 수집하지 않고 있습니다.
수집 기준에 대한 페이지를 만들어 별도의 설명을 추가하도록 하겠습니다!

이상 더 궁금하신게 있으시면 댓글 주세요!

**Comment by rscarrera27** [comment]
Organization에 커밋한 것도 수집이 잘 되지 않는것같습니다

**Comment by rscarrera27** [comment]
이슈 생성과 팔로워 수 및 스타 집계가 제대로 되지 않는것같아요

**Comment by kingbbode** [comment]
> 이슈 생성과 팔로워 수 및 스타 집계가 제대로 되지 않는것같아요

확인해볼게요. 매번 감사합니다 :)

**Comment by kingbbode** [comment]
이슈가 오래되어 close 합니다.
수집 관련하여 문의가 있으면 언제든지 다시 열어주세요 :)
