### ISSUE TITLE
사용자 프로필 내의 시즌별 조회 팝업의 위치 문제

### ISSUE THREAD

**Issue by hongsii** [10duck/issues#10]
사용자 프로필에서 시즌이 오래될수록 팝업 위치가 점점 위로 올라가서 메뉴랑 겹치는 문제가 발생합니다.

<초기 팝업>
<img src="https://user-images.githubusercontent.com/23633847/51123442-711a0080-185f-11e9-81ef-7cfa190790af.png" width="300px" height="300px" />

<오픈 베타 1차 선택>
<img src="https://user-images.githubusercontent.com/23633847/51122573-82620d80-185d-11e9-9d1b-bdd8e70ae00e.png" width="300px" height="300px" />

**Comment by kingbbode** [comment]
UI 변경으로 수정되었네요 :) 
감사합니다.
