### ISSUE TITLE
[제안] Top 50 소속

### ISSUE THREAD

**Issue by SeonHyungJo** [10duck/issues#11]
현재 Top 50 소속의 경우 프로필의 정보를 가져와서 같은 소속을 카운트해서 보여주는 것 같습니다. 

그런데 한가지 @로 구분을 못하는게 아쉽습니다. 혹시 @로 구분을 해서 카운트가 가능할까요?

**Comment by kingbbode** [comment]
감사합니다! :) 반영하겠습니다!

**Comment by kingbbode** [comment]
@SeonHyungJo 
고민을 해보았으나 다른 의도로 @를 사용하시는 분들도 발견하여 이 이슈는 반영을 못하게 되었습니다.
늦은 회신 죄송합니다. (_ _)

**Comment by SeonHyungJo** [comment]
@kingbbode  아 아쉽군요 늦게라도 회신해주셔서 고맙습니다 :+1:
