### ISSUE TITLE
[FE] 몇가지 건의

### ISSUE THREAD

**Issue by luiseok** [10duck/issues#12]
안녕하세요?

개발자들이 놀이터(?)처럼 활동할 수 있는 사이트를 만들어 주셔서 먼저 감사하다는 말씀을 드립니다.
사이트를 둘러보고, 몇가지 Frontend 부분에서 제안 드리고자 이슈를 등록하게 되었습니다.

1. 폰트들이 px로 설정되어 있는데, 이 픽셀값들이 4k,5k 해상도에서 다소 작아보여서 보기가 조금 힘듭니다ㅠㅠ
-> 12px 텍스트를 14px나 16px정도로 올리시는것에 대해서 어떻게 생각하시나요..?
-> body {} 부분 css에 14px로 설정되어 있던데, 폰트 크기의 단위를 px에서 rem으로 변경하는 것에 대해서는 어떻게 생각하시나요? [EM vs REM vs PX – Why you shouldn't “just use pixels”](https://engageinteractive.co.uk/blog/em-vs-rem-vs-px)

2. 내 프로필 > Stack 입력 하는 부분에서 더 나은 사용성을 가진 UI/UX를 제안드립니다.
 -> 현재는 하단의 (1)+ 버튼 클릭 -> (2)카테고리선택 -> (3) 기술 선택 의 과정을 거쳐야 합니다. 3번의 클릭이나 하게 만드는(...!) 다소 불편한 UX를 가지고 있는데,
 -> 이를 각각의 카테고리(?)에 auto complete 또는 select form을 두어 바로 선택할 수 있도록 한다면 좋을것 같습니다.
 -> 아울러 카테고리의 종류가 다양하지 않아 새로운 기술을 추가할 수 있도록 기능적인 부분에서도 개선이 되면 좋을것 같습니다.

둘러보다가..조금 불편해보이는 몇가지 이슈들을 적어보았는데, 모두 다 반영이 되지는 않더라도 꼭 폰트 부분은...개선이 되면 좋을것 같습니다..!
감사합니다

**Comment by kingbbode** [comment]
문의 감사합니다 :)
두 가지 내용 모두 너무 감사합니다! 빠르게 적용해보겠습니다!

**Comment by kingbbode** [comment]
1. css 무식자들이 모여 만든 서비스라.. 범용적인 UI Framwork를 사용하였더니 말씀하신 적용이 쉽지는 않은 것으로 파악됩니다. 12px 이하로 보이는 부분은 강제로 수정하였으나 추가로 보기 어려우신 부분이 있다면 정확한 위치를 말씀 부탁드립니다 ㅜㅜ

2. 자동완성 기능을 추가하였습니다. 
(+) 스택 추가를 위해 https://github.com/10duck/stack-store 저장소를 생성하였으나 사용이 제대로 되지 않고 있었습니다 :) 사이트 내에 기재하여 안내할 수 있도록 수정하겠습니다.

**Comment by luiseok** [comment]
@kingbbode 빠른 피드백 감사드립니다..!
