### ISSUE TITLE
일일 커미터 산정 문제

### ISSUE THREAD

**Issue by nokchax** [10duck/issues#15]
안녕하세요 용근님!
매달 마지막 날 커밋 시간이 늦은 경우 일일 커미터 계산에서 빠지는거 같아요
확인 부탁드립니다 :)

**Comment by kingbbode** [comment]
@nokchax 
광현님 감사해요 :)
확인해볼게요.

**Comment by kingbbode** [comment]
@nokchax 
현재로서는 일일커미터 뱃지 발급에 대한 이상은 없어보이네요 :)
늦은 커밋을 고려하여 최종집계는 시즌 마감 후 2~3일 후에 진행하고 있어요.
참고 부탁드려요!
