### ISSUE TITLE
기술스택에 Angular는 없고 Angularjs만 있어요.

### ISSUE THREAD

**Issue by JUNWOO45** [10duck/issues#16]
Angularjs는 Angular 1버전이고, 2버전부터는 Angular라고 합니다.ㅎㅎ
Angular도 선택할 수 있게 만들어주세요~

**Comment by kingbbode** [comment]
@JUNWOO45 감사합니다 :) 추가 완료되었습니다.

**Comment by JUNWOO45** [comment]
@kingbbode 감사합니다 :0
