### ISSUE TITLE
1월 31일 Week Data가 이상합니다.

### ISSUE THREAD

**Issue by Rebwon** [10duck/issues#18]
https://github.com/Rebwon 1월 31일 제 커밋은 4번인데, 코덕 Week Data에서는 7커밋으로 나옵니다.
수동 갱신 요청 후에 이런 상황이 발생한 것 같은데 확인 부탁드려요.

**Comment by kingbbode** [comment]
https://github.com/10duck/issues/issues/20

해당 이슈와 동일한 현상으로, 서버 작업 중 누락이 있었습니다.
점수 재산정 예정입니다.  감사합니다. 👍
