### ISSUE TITLE
팔로워 산정 문제

### ISSUE THREAD

**Issue by baeharam** [10duck/issues#19]
제 팔로워는 현재 12명인데 11명으로 나옵니다.
제대로 갱신이 이루어지지 않은 것 같습니다. 감사합니다.

**Comment by kingbbode** [comment]
@baeharam 
안녕하세요. 팔로워 정보는 3일 마다 로그인 기준으로 업데이트 되고 있습니다.
갱신주기를 더 짧게 가져가는 것을 논의해보겠습니다 :)
