### ISSUE TITLE
아무런 깃헙 활동이 없었음에도 불구하고 수동갱신 요청을 누를 때마다 점수가 올라갑니다

### ISSUE THREAD

**Issue by ssosso** [10duck/issues#2]
아래와 같은 현상이 있습니다. 확인 부탁드립니다:)

 - 23일 commit 1번 이후로 현재까지 아무런 활동을 하지 않았는데 수동갱신 요청을 누를 때마다 점수가 올라갑니다.
 - 원인을 알기 위해서 어떤 변동사항이 있는지 확인해보니 현재가 24일임에도 불구하고 이미 지난 날짜인 23일의 commit 횟수가 수동갱신을 할 때마다 1개씩 증가하는 걸 발견했습니다.

**Comment by kingbbode** [comment]
제보 감사합니다!! 수정하여 이번 시즌 초기화 후 재배치를 해보겠습니다! 감사합니다 :)

**Comment by kingbbode** [comment]
@ssosso 수동요청 갱신을 구동하는 서버시간의 문제가 있었네요! 감사합니다.
