### ISSUE TITLE
수동갱신 요청문제

### ISSUE THREAD

**Issue by baeharam** [10duck/issues#20]
현재 수동갱신요청시 커밋횟수가 +4 되는 버그가 있습니다.
처리 부탁드립니다. 감사합니다.

**Comment by kingbbode** [comment]
@baeharam 
이벤트 갱신 서버 작업 중 서버 시간 설정에 대한 실수가 발생하여 오처리 되었습니다.
제보 감사합니다 👍 👍 

(작업 일 기준으로 점수 재계산 작업을 진행하여 오처리에 대한 보정 작업이 이루어질 예정입니다.)
