### ISSUE TITLE
일일커밋 중인데 점수가 오르지 않습니다.

### ISSUE THREAD

**Issue by Rebwon** [10duck/issues#22]
일일 커밋을 진행중인데 3일전부터 점수가 오르지 않습니다. 확인부탁드립니다 :)

**Comment by kingbbode** [comment]
계산 과정 중 사용하는 API 의 변경이 있어 제대로 점수 계산이 되지 못하였습니다 :)
일부 계산을 새로운 로직으로 작성하여 변경에 대응 중 입니다!

제보 감사합니다.

**Comment by kingbbode** [comment]
점수가 갱신되지 않는 문제는 해결되었으며, 일부 버그 수정을 위해 새로운 버전을 작성 중 입니다 :)
감사합니다.
