### ISSUE TITLE
수동 갱신 요청시 점수 하락 현상이 있습니다.

### ISSUE THREAD

**Issue by ankiwoong** [10duck/issues#23]
안녕하세요.

수동 커밋 요청 버튼을 클릭하면 점수가 내려가는 현상이 있습니다.

이것이 정상인지 궁금합니다.

감사합니다.

**Comment by ksundong** [comment]
저도 동일증상인듯 합니다 ㅋㅋㅋ..
기록은 있는데 점수가 하나도 안느네요...

**Comment by kingbbode** [comment]
확인해보도록 할게요 :) 

@ankiwoong
@ksundong 

확인하신 날짜가 있을까요?

**Comment by ankiwoong** [comment]
> 확인해보도록 할게요 :)
> 
> @ankiwoong
> @ksundong
> 
> 확인하신 날짜가 있을까요?
안녕하세요!
@kingbbode 님
현재도 해보았는데 점수가 누를때마다 내려갑니다!
점수 복구 되는것은 다되는지 모르겟지만 다음날이면 올라와있더라고요.
누를때마다 내려가는포인트는 대략 6~9점 사이 인거같습니다!

**Comment by kingbbode** [comment]
@ankiwoong 일단 트래킹을 위해 로그를 추가하여 배포하였습니다.
현상 재현시 시점을 남겨주시면 감사하겠습니다.
로그는 지속 확인하여 결과 공유드리겠습니다.

**Comment by ankiwoong** [comment]
> @ankiwoong 일단 트래킹을 위해 로그를 추가하여 배포하였습니다.
> 현상 재현시 시점을 남겨주시면 감사하겠습니다.
> 로그는 지속 확인하여 결과 공유드리겠습니다.

@kingbbode 
넵!
확인 감사드립니다!
지금은 버튼을 누르니 다시 점수가 복구 되었습니다.
점수가 하락 하면 시간대역 남겨드리겠습니다.
빠른 확인 정말로 감사드립니다!

**Comment by ankiwoong** [comment]
@kingbbode 
한번 더 누르니 방금 재현되었습니다!
257에서 233으로 내려갔습니다.
2020.04.09 15:53 입니다!

**Comment by kingbbode** [comment]
@ksundong @ankiwoong 
분산된 활동 정보를 합치는 과정에 버그가 존재하여 수정하여 점수 재갱신을 하였습니다.

제보 정말 감사합니다.

**Comment by ankiwoong** [comment]
@kingbbode 
이렇게 재미있는것을 만들어주셔서 정말로 감사합니다.
의미부여가 잘되고 있어요!
