### ISSUE TITLE
4월 6일 업데이트 이 후 점수 산정 방식이 변경되었는지 궁금합니다!

### ISSUE THREAD

**Issue by ofnullable** [10duck/issues#24]
20년 03시즌에 분명 첫 화면에 보였는데
일일커밋 뱃지도 top10 뱃지도 안달렸네요..ㅠㅠ

**Comment by kingbbode** [comment]
@ofnullable 님 안녕하세요 :)

4월 6일 업데이트시 불가피한 이유로 **커밋일수 계산을 파싱 기반에서 데이터 기반으로 변경하였습니다.**

@ofnullable 님의 3월 9일, 3월 12일 활동으로 인해 차이가 발생하게 되었습니다.

코덕의 그래프상 9일, 12일 활동이 인정되지 않았는데요. 코덕에서 `이슈` 이벤트는 오픈소스 활동에 대한 활동을 수집하기 위해 점수를 계산하고 있기 때문에, 자신의 프로젝트에서 이슈 발행은 인정을 하지 않고 있습니다.

`github contributions map` 에서는 해당 날짜의 활동이 인정되어 칸이 채워져 있습니다.

커밋일수 계산 로직을 `github contributions map` 에서 `코덕 데이터` 로 변경됨에 따라 연속 커밋 가산점이 낮아져 점수가 낮아진 걸로 확인됩니다.

4월부터 코덕의 점수 계산 방식은 위와 같이 말씀드린데로 변경될 것이기 때문에, 3월의 활동에 대해서는 기존 기준의 재계산을 통해 뱃지와 점수를 갱신하도록 하겠습니다.

처리가 완료되는데로 이 이슈에 추가 코멘트를 작성하겠습니다.

관심가져주셔 감사합니다!

**Comment by ofnullable** [comment]
앗 빠른 답변 감사드립니다!
