### ISSUE TITLE
버그 제보 드립니다

### ISSUE THREAD

**Issue by ankiwoong** [10duck/issues#25]
안녕하세요!

버그 제보 드립니다.

통계 부분에 코덕 레벨 분포도에 정렬이 이상하게 되고 있습니다.

확인 한번 해주세요.

**Comment by kingbbode** [comment]
@ankiwoong 

정렬에 대한 제한을 두지 않았지만, 레벨 순서대로 보이면 더 좋을 것 같네요.
별게 작업을 생성하여 통계 부분을 개선 예정입니다.

감사합니다 :)
