### ISSUE TITLE
로그인 안되는 현상 제보드립니다

### ISSUE THREAD

**Issue by winterlood** [10duck/issues#26]
다른분들도 그러신지 모르겠지만,

로그인 버튼을 누르면 index페이지로 리다이렉트만 되고 

로그인이 되지 않는 현상을 발견하여 개발자도구의 네트워크탭으로 확인한 결과입니다..

![image](https://user-images.githubusercontent.com/46296754/80483488-23ac9e80-8991-11ea-9537-fc4e8302af7d.png)

![image](https://user-images.githubusercontent.com/46296754/80483418-04ae0c80-8991-11ea-9a9c-facaf068e804.png)

**Comment by kingbbode** [comment]
@winterlood 
안녕하세요 :) 사용자 테이블쪽 이모지 사용에 대한 처리가 안되어있어 정보 수정해두었습니다.
제보 감사합니다.
