### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by ankiwoong** [10duck/issues#27]
08.12 / 13 커밋 수치가 정상적으로 체크가 되지않고 있습니다.

12일 수치 커밋 15 푸시 15

13일 수치 커밋 7 푸시 7

이렇게 수치 상으로 나오는데요.

코덕에서는 0으로 나오고 있습니다.

수치 체크 확인 부탁드리겟습니다.

동기 부여 주셔서 감사드립니다.

**Comment by kingbbode** [comment]
감사합니다 👍 
데이터베이스 디스크 용량 문제가 있었고, 증설하여 해소되었습니다.
제보 감사드립니다.
