### ISSUE TITLE
Private Repository 산정 문의

### ISSUE THREAD

**Issue by KangDroid** [10duck/issues#29]
안녕하세요, CODUCK에 갓 가입한 신규 회원입니다.

현재 개인 프로젝트 중, 프라이빗으로 2월 5일부터 개발하던 레포가 4개 정도 되는데, 
공개 시점이 CODUCK 가입 이후에 공개하게 되었습니다. 

그러나, "소통" 게시글을 찾아본 결과, 프라이빗 레포는 가입 이후에는 산정이 안된다는 글을 보았는데, 
혹시 레포가 오픈된 현 시점에서 재반영이 될 수 있는지 문의드립니다.

감사합니다 :)

**Comment by kingbbode** [comment]
@KangDroid 
안녕하세요!
해당 레파지토리의 이름을 알 수 있을까요?

**Comment by KangDroid** [comment]
@kingbbode 
빠른 답변 감사합니다!

해당 레포지토리 이름[링크]은 다음과 같습니다! :
https://github.com/KangDroid/CLMasterServer
https://github.com/KangDroid/CLClient
https://github.com/KangDroid/CLNodeServer
https://github.com/KangDroid/CLNodeRegister

**Comment by kingbbode** [comment]
@KangDroid 
아쉽게도 깃헙에도 공개 이전 활동 이벤트는 여전히 private 상태로 남아있어 산정이 어려울 것 같습니다ㅜㅜ

**Comment by KangDroid** [comment]
@kingbbode 앗 아쉽군요 ㅠㅠ

해당 내용 확인 하였습니다. 답변 감사드립니다!
