### ISSUE TITLE
수동갱신을 요청했는데도 '최대 연속 커밋일 수'가 갱신되지 않습니다.

### ISSUE THREAD

**Issue by ssosso** [10duck/issues#3]
아래와 같은 현상이 있습니다. 확인 부탁드립니다:)

- 18일부터 23일까지 6일간 연속 커밋하였는데 수동갱신해도 프로필 페이지 첫 번째 패널에 있는 '최대 연속 커밋일 수'가 5일로 표시됩니다.
- 프로필 페이지 세 번째 패널에 있는 그래프에는 6일간의 커밋 횟수가 표시되고 있습니다.

**Comment by kingbbode** [comment]
연속 커밋일 수는 배치 작업을 통해서만 갱신을 했었는데, 이번에 수정을 해야겠습니다 감사합니다!
