### ISSUE TITLE
탈퇴기능이 있나요?

### ISSUE THREAD

**Issue by HugoParkk** [10duck/issues#32]
현재 저의 private였던 repository에 있던 commit들이 조회가 안되서 탈퇴하고 다시 가입하려고 하는데 탈퇴기능이 없는것같아서 문의드립니다.

**Comment by kingbbode** [comment]
@pokoed 님 안녕하세요.
서비스에서 직접 탈퇴할 수 있는 기능이 만들어져있지 않네요ㅜㅜ
가급적 빠르게 기능을 만들도록 하겠습니다.

임시로 직접 탈퇴를 시켜드릴 수 있는데, 원하실까요?
(참고로 코덕에서는 private 레포에 대한 정보를 수집하지 않습니다)

**Comment by HugoParkk** [comment]
@kingbbode 앗 그부분은 괜찮습니다! 답변 감사합니다.
