### ISSUE TITLE
수동갱신요청 이후 랭킹에 갱신된 점수가 반영되는 속도가 느립니다

### ISSUE THREAD

**Issue by ssosso** [10duck/issues#4]
안녕하세요^^
수동갱신 요청 이후에 랭킹을 살펴보면 갱신된 점수가 바로 반영되지 않는 것 같습니다.
(680으로 갱신되었음에도 아직 랭킹페이지에는 620)
보통 갱신이 되면 갱신된 점수로 다시 한번 랭킹을 확인하고 싶을 것 같은데 반영 시점이 차이가 나는 것은 의도한 바이신지 궁금합니다.

**Comment by kingbbode** [comment]
네! 맞습니다 :)

랭킹, 분석 데이터는 일정 주기로 갱신되는 데이터입니다!

이런 데이터의 경우 언제 갱신되었는지, 어떤 시간이 기준인지 표기를 해야겠네요!
