### ISSUE TITLE
마우스 커서 모양

### ISSUE THREAD

**Issue by SeonHyungJo** [10duck/issues#5]
흥미로운 프로젝트 잘 사용하고 있습니다. 
간헐적으로 들어가서 즐겨보고 있습니다. 

최근 들어가서 보는데 메인홈에서 소식란은 CSS { cursor : pointer }로 되어있어 이쁘게 나오는데 채용정보나 세미나 정보란은 CSS가 들어가 있지 않아 auto로 나오고 있습니다. UI적으로 수정이 이루어지면 좋을 것 같습니다.

**Comment by kingbbode** [comment]
감사합니다 :)

css 알못인 개발자들이다보니 실수가 많네요..
수정해보겠습니다!

**Comment by kingbbode** [comment]
수정되었습니다 :)
