### ISSUE TITLE
기술스택 정렬

### ISSUE THREAD

**Issue by hongsii** [10duck/issues#7]
안녕하세요. 개발하신 사이트가 동기를 부여해줘서 유용하게 사용하고 있습니다! 사이트를 이것저것 둘러보던 중 기술스택을 추가, 삭제할 때마다 정렬이 변경되던데 정렬 순서가 이상해보여서 혹시 버그가 아닐까해서 이슈를 등록합니다.

예를 들어, TOOL에 Eclipse, Intellij, Git을 추가했을 때 순으로 `Intellij -> Eclipse -> Git` 정렬되었다가 다른 기술 영역(같은 TOOL인 경우도)에 기술스택을 변경하면 하면 `Git -> Eclipse -> Intellij` 되었다가 변경될 때마다 앞의 두 정렬이 번갈아 가면서 나옵니다. (앞의 예시와 같은 순서가 아닌 경우도 존재했습니다.)

이왕이면 사용자가 추가한 순서, 알파벳 순서, 기술스택의 순서와 같이 일관된 정렬 순서를 유지하는게 좋지 않을까 싶어서 의견을 남겨봅니다.

**Comment by kingbbode** [comment]
@hongsii 
제보 감사합니다!

**Comment by kingbbode** [comment]
수정 되었습니다. 너무 늦어 죄송합니다 :)
