### ISSUE TITLE
로그인 되지 않은 상태에 있어 로그아웃 버튼 활성화 상태

### ISSUE THREAD

**Issue by SeonHyungJo** [10duck/issues#8]
처음 로그인이 되지 않은 상태에서 접속시 상단에 로그아웃버튼이 나와있습니다.
의도하신건지는 모르겠지만 초기접속시 로그인이 되어있는 상태처럼 보입니다.

**Comment by kingbbode** [comment]
@SeonHyungJo 

감사합니다 👍
