### ISSUE TITLE
1월6일 업데이트 관련 이슈입니다.

### ISSUE THREAD

**Issue by Integerous** [10duck/issues#9]
https://github.com/10duck/coduck-comment/issues/21#issuecomment-453902752

위의 링크에 작성했으나, 확인하시기 힘들 것 같아 여기로 옮겼습니다.

**Comment by kingbbode** [comment]
@Integerous 

아이고 감사합니다 :) 일단 해제 시켜놓겠습니다.

기능은 추후 업데이트하겠습니다!

**Comment by kingbbode** [comment]
2월 6일 업데이트 되었습니다 :)

**Comment by kingbbode** [comment]
2월 6일 업데이트 되었습니다 :)
